#!/bin/sh

DAEMON=/usr/bin/aesdsocket
DAEMON_ARGS="-d"
NAME=aesdsocket
PIDFILE=/var/run/${NAME}.pid

case "$1" in
    start)
        echo "Starting $NAME"
        start-stop-daemon --start \
            --name $NAME \
            --make-pidfile \
            --pidfile $PIDFILE \
            --exec $DAEMON \
            -- $DAEMON_ARGS
        ;;
    stop)
        echo "Stopping $NAME"
        start-stop-daemon --stop \
            --name $NAME \
            --pidfile $PIDFILE \
            --signal TERM \
            --retry 5
        rm -f $PIDFILE
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
